# Generated by Django 3.2.21 on 2023-10-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter_Reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='dis_date',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
