# Generated by Django 3.2.21 on 2023-10-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter_Reader', '0002_auto_20231024_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='amount',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
